### ISSUE TITLE
Early 2018 plan

### ISSUE THREAD

**Issue by pwyq** [pwyq/pwyq.github.io#1]
Haven't update the site in a century (~4 months); still, it's long enough for me to forget everything.

## TODO
- [ ] fix footer copyright year from 2017 to 2018 (it's should be auto set)
- [ ] move resume page out of guide-bar
- [ ] place resume page in about page
- [ ] post a post about sudoku sovler
- [ ] post a post about AI
- [ ] update the working-without-mouse post
